services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uv run fastapi run app/main.py

volumes:
  db_data: